name: Generate Activity Graph

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-readme-assets
  cancel-in-progress: false

jobs:
  graph:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create assets folder
        run: mkdir -p assets/generated

      - name: Download activity graph
        run: |
          curl -L "https://github-readme-activity-graph.vercel.app/graph?username=anasemadanas&theme=react-dark" -o assets/generated/activity-graph.svg

      - name: Commit graph
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  
            git add assets/generated/activity-graph.svg
  
            if git diff --cached --quiet; then
              echo "No changes to commit"
              exit 0
            fi
  
            git commit -m "Update activity graph [skip ci]"
            git pull --rebase origin main
            git push origin main
